[package]
name = "pba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
nalgebra = "0.32.3"
rand = "0.8.5"
rand_seeder = "0.2.3"
rayon = "1.8.0"
